# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - trygain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_91c00223fdb64887831c0b516eae2b9b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6bea2261e84a47cbb803939a2f83914f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_91c00223fdb64887831c0b516eae2b9b }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'trygain'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0ceb3a074d2b45f8b6383e687ed3b91d }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_91c00223fdb64887831c0b516eae2b9b }}/appsvc/staticsite:${{ github.sha }}'